import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  Show,
  UserButton,
} from "@clerk/nextjs";
import { Plus } from "lucide-react";
import Link from "next/link";
import MobileNav from "@/components/mobileNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CodeCritic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <nav className="sticky top-0 z-50 flex justify-between items-center px-6 py-4 border-b border-zinc-200 dark:border-zinc-800 bg-white">
            <span className="font-semibold text-2xl text-blue-600">CodeCritic</span>
            <div className="hidden md:flex items-center gap-4">
              <Show when="signed-in">
                <div className="flex items-center gap-5">
                <Link href="/" className="hover:text-zinc-900 dark:hover:text-zinc-100 transition animate-fade-in">
                  Home
                </Link>
                <Link href="/dashboard" className="hover:text-zinc-900 dark:hover:text-zinc-100 transition animate-fade-in">
                  Dashboard
                </Link>
                <Link href="/profile" className="hover:text-zinc-900 dark:hover:text-zinc-100 transition animate-fade-in">
                  Profile
                </Link>
                </div>
              </Show>
              <Link href="/submit" className="border border-gray-200 inline-flex items-center gap-2 bg-black text-white font-medium px-3 py-1.5 rounded-md hover:text-bg-500 dark:hover:bg-gray-100 transition">
                Post a Review Request
              </Link>
              <Show when="signed-out">
                <SignInButton mode="modal"><button className="text-sm font-medium px-3 py-1.5 rounded-md border border-gray-200 hover:bg-gray-100 dark:hover:bg-gray-500 transition">Sign In</button></SignInButton>
                <SignUpButton mode="modal"><button className="text-sm font-medium px-3 py-1.5 rounded-md bg-black text-white border border-gray-800 hover:bg-gray-500 dark:hover:bg-gray-100 transition">Sign Up</button></SignUpButton>
              </Show>
              <Show when="signed-in">
                <UserButton />
              </Show>
            </div>
            <MobileNav/>
          </nav>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}